# Installation

- 파이썬 버전 체크 (Python version Check)
- 파이토치 설치 (PyTorch Installation)
- 쿠다 및 CuDNN 체크 (Cuda & CuDNN Check)

## 1. Python Version Check
파이썬 버전 체크

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import sys
print(sys.version)

3.7.10 (default, May  3 2021, 02:48:31) 
[GCC 7.5.0]


## 2. PyTorch Installation
- 구글 콜라브 버전에 따라 파이토치가 설치되어 있을 수도 있고 아닐 수도 있음
- 설치가 안 되어 있을 경우 아래와 같은 명령어로 설치
- !pip3 install torch torchvision

In [4]:
import torch

In [5]:
!pip3 install torch torchvision

## 3. Cuda & cuDNN Version Check
- 파이토치를 통해 각각 몇 버전이 설치되어 있는지 확인

In [7]:
import torch

print("Torch version: {}".format(torch.__version__))
print("cuda version: {}".format(torch.version.cuda))
print("cuDNN version: {}".format(torch.backends.cudnn.version()))

Torch version: 1.8.1+cu101
cuda version: 10.1
cuDNN version: 7603


## 4. Command Line Cuda & cuDNN Check
- Cuda 및 CuDNN 버전은 Command Line 명령어로도 확인 가능

In [8]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0


In [9]:
!cat /usr/include/x86_64-linux-gnu/cudnn_v*.h | grep CUDNN_MAJOR -A 2

#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
--
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 4
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#endif /* CUDNN_VERSION_H */


# 5. PyTorch CPU & GPU Tensor Check
- 파이토치 텐서를 생성해봄으로써 제대로 설치 되었는지, 잘 동작하는지 확인

### 5-1 Create CPU tensor

In [10]:
# https://pytorch.org/docs/stable/torch.html?highlight=tensor#torch.tensor
# 0으로 된 2 x 3 형태의 텐서 생성

cpu_tensor = torch.zeros(2,3)
print(cpu_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 5-2 Allocate tensor on GPU

In [11]:
# https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.device
# 어느 장치(CPU 혹은 GPU)에 텐서를 올릴지 지정
# torch.device 함수를 사용하여 GPU로 장치를 지정
device = torch.device('cuda')

# https://pytorch.org/docs/stable/cuda.html?highlight=available#torch.cuda.is_available
# GPU가 사용 가능한지 확인
if torch.cuda.is_available():  
  # https://pytorch.org/docs/stable/tensors.html?highlight=#torch.Tensor.to
  # CPU에 있었던 텐서를 to 함수를 이용해 지정해놓은 장치(여기서는 GPU)로 올리기
  gpu_tensor = cpu_tensor.to(device)
  print(gpu_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')


### 5-3 Reallocate tensor back on CPU

In [12]:
# device 함수와 to 함수를 이용해 GPU에 있던 텐서를 다시 CPU로 옮기기
cpu_tensor_back = gpu_tensor.to(torch.device('cpu'))
cpu_tensor_back

tensor([[0., 0., 0.],
        [0., 0., 0.]])