# 단순한 기울기 계산 

- z = 2x^2 + 3



In [1]:
# 2 x 3 shape의 tensor 생성
# tensor 안에는 임의의 난수가 들어감

import torch
X = torch.Tensor(2, 3)
X

tensor([[2.5799e-08, 3.0866e-41, 3.7835e-44],
        [0.0000e+00,        nan, 3.0866e-41]])

In [2]:
# tensor를 원하는 값으로 초기화하려면 인수로 값의 배열을 전달

X = torch.tensor([[1, 2, 3], [4, 5, 6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
# x를 [2.0, 3.0]의 값을 가진 텐서로 초기화하고 기울기 계산을 True로 설정
# 텐서에 대한 기울기를 저장하고 싶을 때 requires_grad = True로 설정

x = torch.tensor(data=[2.0, 3.0], requires_grad = True)
y = x ** 2
z = 2 * y + 3    # 기울기 계산을 True로 지정했으므로 z에 연산 그래프의 결과값이 저장됨

In [4]:
x

tensor([2., 3.], requires_grad=True)

In [5]:
y

tensor([4., 9.], grad_fn=<PowBackward0>)

In [6]:
z

tensor([11., 21.], grad_fn=<AddBackward0>)

- autograd.backward() 참고 : https://pytorch.org/docs/stable/autograd.html?highlight=backward#torch.autograd.backward

In [7]:
# 목표값 지정

target = torch.tensor([3.0, 4.0])

In [8]:
# z와 목표값의 절대값 차이를 계산
# backward는 스칼라 값에 대해 동작하므로 길이 2짜리 텐서인 loss를 torch.sum을 통해 스칼라 값으로 변경

loss = torch.sum(torch.abs(z - target))
loss

tensor(25., grad_fn=<SumBackward0>)

In [9]:
# 스칼라 값이 된 loss에 대해 backward를 적용

loss.backward()

In [10]:
# 여기서 y와 z는 기울기가 None으로 나오는데 이는 x, y, z중에 x만이 leaf node이기 때문
print(x.grad, y.grad, z.grad)

tensor([ 8., 12.]) None None


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  


- loss.backward() 함수를 호출하면 연산 그래프를 따라가며 잎 노드(leaf node) x에 대한 기울기를 계산함
- 잎 노드(leaf node) : **다른 변수를 통해 계산되는 y나 z가 아니라 그 자체가 값인 x 같은 노드**를 의미