### Numpy 모듈의 호출

In [2]:
import numpy as np

### Array의 생성

In [3]:
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [4]:
test_array.dtype      # Array(배열) 전체의 데이터 Type을 반환함

dtype('float64')

In [5]:
test_array = np.array([1, 4, 5, "8"], float)    # String Type의 데이터를 입력해도
print(test_array)
print(type(test_array[3]))                      # Float Type으로 자동 형변환을 실시
print(test_array.dtype)                         # Array(배열) 전체의 데이터 Type을 반환함
print(test_array.shape)                         # Array(배열)의 shape을 반환함

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [6]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [7]:
tensor = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [8]:
np.array(tensor, int).ndim

3

In [9]:
np.array(tensor, int).size

48

In [10]:
np.array([[1, 2, 3], [4.5, 5, 6]], dtype = int)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype = np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [12]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype = np.float32).nbytes   # 32bits = 4bytes → 6개 values * 4 bytes

24

In [13]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype = np.int8).nbytes   # 8bits = 1byte → 6개 values * 1 bytes

6

In [14]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype = np.float64).nbytes   # 64bits = 8bytes → 6개 values * 8 bytes

48