In [1]:
import numpy as np

### boolean index

- numpy 배열은 특정 조건에 따른 값을 배열 형태로 추출할 수 있음
- Comparison operation 함수들도 모두 사용가능

In [2]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [3]:
test_array[test_array > 3]     # 조건이 True인 index의 element만 추출

array([4., 8., 9., 7.])

In [4]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [5]:
A = np.array([[12, 13, 14, 12, 16, 14, 11, 10, 9],
              [9, 8, 17, 13, 10, 18, 13, 12, 11]])
B = A < 15
B.astype(np.int)    # Boolean 타입인 B를 astype으로 integer 타입으로 변경(True : 1, False : 0)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 0, 1, 1, 1]])

### fancy index

- numpy array를 index value로 사용해서 값을 추출하는 방법

In [6]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)    # 반드시 integer로 선언
a[b]                                     # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

In [7]:
a.take(b)   # take 함수 ★ : bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

- Matrix 형태의 데이터도 가능

In [9]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)

a

array([[ 1.,  4.],
       [ 9., 16.]])

In [10]:
a[b,c]   # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])