In [1]:
import numpy as np

### All & Any

- Array의 데이터 전부(and) 또는 일부(or)가 조건에 만족 여부 반환

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.any(a > 5), np.any(a < 0)    # any : 하나라도 조건에 만족한다면 true(or)

(True, False)

In [4]:
np.all(a > 5), np.any(a < 10)    # all : 모두가 조건에 만족한다면 true(and)

(False, True)

### Comparison operation 1

- Numpy는 배열의 크기가 동일할 때 element 간 비교의 결과를 Boolean type으로 반환

In [5]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [6]:
test_a == test_b

array([False, False, False])

In [7]:
(test_a > test_b).any()

True

### Comparison operation 2

In [8]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)     # and 조건의 condition

array([ True, False, False])

In [9]:
b = np.array([True, False, True], bool)
np.logical_not(b)    # NOT 조건의 condition

array([False,  True, False])

In [10]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)   # OR 조건의 condition

array([ True,  True,  True])

### np.where ★

In [11]:
a

array([1., 3., 0.])

In [12]:
np.where(a > 0, 3, 2)    # where(condition, TRUE, FALSE)

array([3, 3, 2])

In [13]:
a = np.arange(10)
np.where(a > 5)     # Index 값 반환

(array([6, 7, 8, 9], dtype=int64),)

In [14]:
a = np.array([1, np.NaN, np.Inf], float)   # NaN : Not a Number
np.isnan(a)

array([False,  True, False])

In [15]:
np.isfinite(a)   # is finite number

array([ True, False, False])

### argmax & argmin

- array 내 최대값 또는 최소값의 index를 반환

In [16]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
np.argmax(a), np.argmin(a)

(5, 0)

- axis 기반의 반환

In [19]:
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [20]:
np.argmax(a, axis = 1), np.argmin(a, axis = 0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))