In [1]:
import numpy as np

### Operations b/t arrays

- Numpy는 array 간의 기본적인 사칙 연산을 지원함

In [3]:
test_a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [4]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [5]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
test_a * test_a    # Matrix 내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### Element-wise operations

- Array 간 shape이 같을 때 일어나는 연산

In [7]:
matrix_a = np.arange(1, 13).reshape(3, 4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### Dot product

- Matrix의 기본 연산

In [8]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)

test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

### Broadcasting ★

- <b>shape이 다른</b> 배열 간 연산을 <b>자동으로</b> 지원하는 기능

In [16]:
test_matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
scalar = 3

test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [11]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [12]:
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [13]:
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [14]:
test_matrix // 0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [15]:
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### Broadcasting 예제

In [18]:
test_matrix = np.arange(1, 13).reshape(4, 3)
test_vector = np.arange(10, 40, 10)

In [19]:
test_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
test_vector

array([10, 20, 30])

In [17]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### Numpy performance 1

- timeit : jupyter 환경에서 코드의 퍼포먼스를 체크하는 함수

In [22]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iteration_max = 100000000

vector = list(range(iteration_max))
scalar = 2

In [23]:
%timeit scalar_vector_product(scalar, vector)                # for loop을 이용한 성능

1min 37s ± 11.3 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
%timeit [scalar * value for value in range(iteration_max)]  # list comprehension을 이용한 성능

28.8 s ± 4.86 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
%timeit np.arange(iteration_max) * scalar                    # numpy를 이용한 성능

633 ms ± 197 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Numpy performance 2

- 일반적으로 속도는 for loop < list comprehension < numpy
- 100,000,000번의 loop이 돌 때 약 4배 이상의 성능 차이를 보임
- Numpy는 C로 구현되어 있어, 성능을 확보하는 대신 파이썬의 가장 큰 특징인 dynamic typing을 포기함
- 대용량 계산에서는 가장 흔히 사용됨
- Concatenate처럼 계산이 아닌, 할당에서는 연산 속도의 이점이 없음!!